from  dotenv import load_dotenv # type: ignore
load_dotenv()
from openai import OpenAI
import time

client = OpenAI()

assistant_id = "asst_r2pAThR01WpjNOEAVKbcO2U0"  # 조금 전 생성한 assistant의 ID를 사용합니다.
assistant = client.beta.assistants.retrieve(assistant_id)
thread_id = "thread_ASW07mbTGURl6qoQi63bOnm8"  # 조금 전 생성한  thread의 ID를 사용합니다.
thread = client.beta.threads.retrieve(thread_id)

# assistant와 thread를 이용 하여 Run을 생성합니다.
run = client.beta.threads.runs.create(
  thread_id = thread.id,
  assistant_id = assistant.id
)

# Run은 비동기적으로 실행되기 때문에, 상태를 계속 모니터링 해야 합니다.
# queue 또는 in_progress 상태일 때는 완료가 되지 않은 상태입니다.
# 해당 Run을 검새하여 완료가 될 때까지 계속 상태를 확인합니다.
while run.status == "queued" or run.status == "in_progress":
    print(run.model_dump_json())
    run = client.beta.threads.runs.retrieve(
        thread_id = thread.id,
        run_id = run.id
    )

    time.sleep(0.5)


# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":null,"status":"queued","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}
# {"id":"run_lHjjjsWEiFYJRCL8SDnZsELe","assistant_id":"asst_r2pAThR01WpjNOEAVKbcO2U0","cancelled_at":null,"completed_at":null,"created_at":1713672899,"expires_at":1713673499,"failed_at":null,"file_ids":[],"incomplete_details":null,"instructions":"You are a personal math tutor. Write and run code to answer math questions.","last_error":null,"max_completion_tokens":null,"max_prompt_tokens":null,"metadata":{},"model":"gpt-4-turbo","object":"thread.run","required_action":null,"response_format":"auto","started_at":1713672899,"status":"in_progress","thread_id":"thread_ASW07mbTGURl6qoQi63bOnm8","tool_choice":"auto","tools":[{"type":"code_interpreter"}],"truncation_strategy":{"type":"auto","last_messages":null},"usage":null,"temperature":1.0,"top_p":1.0}